#!/bin/bash

# Usage:
# ./run example_file.ob

# Edit path to where Oberon0 jars are kept

PathToJar="../../../../"

# Specify which artifact jar you would like to use, e.g. oberon0_a5.jar

ObJar="oberon0_a5.jar"

JAR=${PathToJar}${ObJar}

# Build each file specified (if there is more than one)

for file in "$@" 
do
  java -Xss4M -Xmx1800M -jar $JAR $file
done