#!/bin/bash

# Usage:
# ./run example_file.ob

# Edit path to where Oberon0 jars are kept

PathToJar="../../../../"

# Specify which artifact jar you would like to use, e.g. oberon0_a5.jar

ObJar="oberon0_a5.jar"

JAR=${PathToJar}${ObJar}

if [ "$1" == "test" ];
then
  # Build all examples and test that a .c file is NOT generated, as expected
  declare -a examples=("7_bool_lower_limit_for" "7_bool_upper_limit_for"
                       "8_bool_low_limit_case" "8_bool_upper_limit_case"
                       "8_bool_var_case" "9_bool_var_for" 
                       "9_var_bool_high_lim_for" "9_var_bool_low_lim_for"
                       "10_var_bool_upper_lim_case" "11_var_bool_limit_case")
  declare r=0
   for file in ${examples[@]}
    do
      java -Xss4M -Xmx1800M -jar ${PathToJar}oberon0_a5.jar ${file}.ob
      if [[ -f ${file}.c ]]
        then
          r=1
      fi
    done
    if [ "$r" == 1 ]
      then
        exit 1
    fi
else
  # Build each file specified (if there is more than one)
  for file in "$@" 
  do
    java -Xss4M -Xmx1800M -jar $JAR $file
  done
fi