#!/bin/bash

rm -f *.jar
rm -f ./positive/simple_lifted.ob ./positive/simple_pp.ob ./positive/simple.c ./positive/simple.errors
rm -f ./positive/altitude_switch_lifted.ob ./positive/altitude_switch_pp.ob ./positive/altitude_switch.c ./positive/altitude_switch.errors